# Generated by Django 3.0.5 on 2020-09-16 20:36

from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('createdBy', djongo.models.fields.GenericObjectIdField()),
                ('parentTopic', djongo.models.fields.GenericObjectIdField()),
                ('createdAt', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Topics',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('title', models.TextField()),
                ('createdBy', djongo.models.fields.GenericObjectIdField()),
                ('createdAt', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('username', models.TextField()),
                ('email', models.TextField()),
                ('gender', models.TextField()),
                ('createdAt', models.DateTimeField()),
            ],
        ),
    ]
